version: "3"
services:
  payment-app-service:
    build:
      context: ./app-Midtrans
    container_name: payment-app
    ports:
      - '8088:80'
    links:
      - db:db
  radius:
    image: kap0ng/freeradius
    container_name: radius
    command: "tail -f /dev/null"
    restart: always
    depends_on:
      - db 
    links:
      - db:db
    ports: 
      - '1812:1812/udp'
      - '1813:1813/udp'
    env_file:
      - ./service/mysql/mysql.config.env
      - ./config.env
    volumes:
      - ./service/freeradius/clients.conf:/etc/freeradius/3.0/clients.conf

  db:
    image: mariadb:10
    restart: always
    ports: 
      - '3306:3306'
    env_file:
      - ./service/mysql/mysql.config.env
    volumes:
      - "./mysql-data:/var/lib/mysql"
  #phpmyadmin:
  #  image: phpmyadmin
  #  restart: always
  #  ports:
  #    - 8080:80
  #  links:
  #    - db:db
  #  environment:
  #    - PMA_ARBITRARY=1