version: "3"
services:
  radius:
    image: kap0ng/freeradius
    restart: always
    depends_on:
      - db 
    links:
      - db:db
    ports: 
      - '1812:1812/udp'
      - '1813:1813/udp'
    env_file:
      - ./service/mysql/mysql.config.env
      - ./config.env
    volumes:
      - ./service/freeradius/clients.conf:/etc/freeradius/3.0/clients.conf
      - ./service/freeradius/radiusd.conf:/etc/freeradius/3.0/radiusd.conf
      - ./service/freeradius/mods-available/sqlcounter:/etc/freeradius/3.0/mods-available/sqlcounter
      - ./service/freeradius/mods-available/sqlcounter:/etc/freeradius/3.0/mods-enabled/sqlcounter
      - ./service/freeradius/sites-enabled/default:/etc/freeradius/3.0/sites-enabled/default
      - ./service/freeradius/mods-config/sql/counter/mysql/accessperiod.conf:/etc/freeradius/3.0/mods-config/sql/counter/mysql/accessperiod.conf
      - ./service/freeradius/mods-config/sql/counter/mysql/quotalimit.conf:/etc/freeradius/3.0/mods-config/sql/counter/mysql/quotalimit.conf
#  freeradius-doloradius:
#    image: boro/freeradius-daloradius
#    restart: always
#    depends_on:
#      - db 
#    links:
#      - db:db
#    ports: 
#      - '1812:1812/udp'
#      - '1813:1813/udp'
#      - 8000:80
#    environment:
#      - CLIENT_SECRET=testhotspot
#      - CLIENT_NET1=0.0.0.0/0
#      - MYSQL_HOST=db
#      - MYSQL_PORT=3306
#      - MYSQL_DATABASE=radius
#      - MYSQL_USER=root
#      - MYSQL_PASS=rootpass
#      - MYSQL_INIT_DATABASE=true
  db:
    image: mariadb:10
    restart: always
    ports: 
      - '3306:3306'
    env_file:
      - ./service/mysql/mysql.config.env
    volumes:
      - "./mysql-data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db:db
    environment:
      - PMA_ARBITRARY=1