version: "3"
services:
  payment-app-service:
    build:
      context: ./app-Midtrans
    container_name: payment-app
    ports:
      - '8088:80'
    links:
      - db:db
  radius:
    image: 2stacks/freeradius
    container_name: radius
    restart: always
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - ./config.env
    volumes:
      - ./service/freeradius/clients.conf:/etc/raddb/clients.conf    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - '3306:3306'
    env_file:
      - ./service/mysql/mysql.config.env
    volumes:
      - "./mysql-data:/var/lib/mysql"
      - "./service/mysql/radius.sql:/docker-entrypoint-initdb.d/radius.sql"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    links:
      - db:db
    environment:
      - PMA_ARBITRARY=1